import assert from "node:assert/strict";
import { ClassList } from "../src/class-list.js";

const owner = { className: "" };
const list = new ClassList(owner);
list.add("a", "b");
assert.equal(owner.className, "a b");
assert.equal(list.contains("a"), true);
assert.equal(list.length, 2);
list.add("a");
assert.equal(owner.className, "a b", "adding twice adds once");
assert.equal(list.toggle("c"), true);
assert.equal(list.toggle("c"), false);
assert.equal(list.toggle("d", true), true);
assert.equal(list.toggle("d", true), true);
assert.equal(list.toggle("e", false), false);
assert.equal(owner.className, "a b d");
list.remove("a", "zzz");
assert.equal(owner.className, "b d");
assert.equal(list.replace("b", "x"), true);
assert.equal(list.replace("nope", "y"), false);
assert.equal(String(list), "x d");
assert.equal(list.item(1), "d");
assert.equal(list.item(5), null);
assert.deepEqual([...list], ["x", "d"]);
assert.throws(() => list.add(""), (e) => e.name === "SyntaxError");
assert.throws(() => list.add("a b"), (e) => e.name === "InvalidCharacterError");
owner.className = "  p  q ";
assert.deepEqual([...list], ["p", "q"], "className is parsed on whitespace");
console.log("class-list tests: all passed");
